config_version = 14

[bar.default]
capsule = true
end = [
    "tray",
    "notifications",
    "clipboard",
    "network",
    "bluetooth",
    "volume",
    "brightness",
    "battery",
    "control-center",
    "session"
]
margin_ends = 0
radius_top_left = 0
radius_top_right = 0
start = [ "launcher", "wallpaper", "workspaces", "media" ]

[calendar]
enabled = true

    [calendar.account.1528588293]
    provider = "icloud"
    type = "caldav"
    username = "1528588293@qq.com"

[location]
address = "shanghai"

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@DP-2" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-2"]
    box_height = 196.0
    box_width = 810.0
    cx = 1280.0
    cy = 1258.0
    output = "DP-2"
    placement_height = 1440.0
    placement_width = 2560.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-2".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[theme]
builtin = "Catppuccin"
mode = "auto"
shell_mode = "dark"

    [theme.templates]
    community_ids = [ "pywalfox" ]

[wallpaper]
directory = "/home/zheng/Pictures/wallpapers"

    [wallpaper.default]
    path = "/home/zheng/Pictures/wallpapers/self/yuanyuan-guloupu.jpg"

    [wallpaper.last]
    path = "/home/zheng/Pictures/wallpapers/self/yuanyuan-guloupu.jpg"

    [wallpaper.monitors.DP-2]
    path = "/home/zheng/Pictures/wallpapers/self/yuanyuan-guloupu.jpg"

[widget.clock]
format = "{:%a %d %b %H:%M}"