export const SITE = {
  website: "https://114132.xyz/",
  author: "Jaanai Liu",
  profile: "https://github.com/Jaanai-Liu",
  desc: "嵌入式系统工程师 / NixOS 用户 / 持续折腾者。分享开发经验与生活记录。",
  title: "Jaanai's Blog",
  ogImage: "astropaper-og.jpg",
  lightAndDarkMode: true,
  postPerIndex: 4,
  postPerPage: 4,
  scheduledPostMargin: 15 * 60 * 1000,
  showArchives: true,
  showBackButton: true,
  editPost: {
    enabled: false,
    text: "Edit page",
    url: "",
  },
  dynamicOgImage: true,
  dir: "ltr",
  lang: "zh",
  timezone: "Asia/Shanghai",
} as const;
