port = 4242

[[clients]]
hostname = "lz-nb"
ips = ["10.126.0.11"]
position = "left"
activate_on_startup = true

[authorized_fingerprints]
"39:eb:cd:1f:1c:f6:74:86:1a:b0:a1:b3:6b:bf:ac:31:3c:e8:26:da:04:7b:69:e9:c2:9d:12:e8:68:d6:ab:0b" = "lz-nb-new"
