port = 4242

[[clients]]
hostname = "lz-pc"
ips = ["10.126.0.10"]
position = "right"
activate_on_startup = true

[authorized_fingerprints]
"c2:12:c4:d7:23:18:84:82:23:39:38:23:67:3f:91:62:e7:da:9d:a9:88:d2:c2:4b:0b:f8:1a:ea:37:45:91:bc" = "lz-pc"
