port = 4242

[[clients]]
hostname = "lz-pc"
ips = ["10.126.0.10"]
position = "right"
activate_on_startup = true

[authorized_fingerprints]
"18:89:19:61:fd:44:a8:54:6f:85:f4:b9:e3:79:e2:8d:06:1d:70:b0:bd:be:5c:a6:e6:a7:ed:6c:59:c4:ec:cd" = "lz-pc-new"
